// src/routes/set/[slug]/+page.svelte
<script lang="ts">
	import Dates from "$lib/components/Dates.svelte";
    import SetHeader from "$lib/components/SetHeader.svelte";
	import OpenGraphMeta from "$lib/components/OpenGraphMeta.svelte";

    const { data } = $props();
    const Writeup = data.content;
    const images = data.metadata.photos;
</script>

<main class="set-main">
    <OpenGraphMeta
        propTitle={data.metadata.name}
        image={images[data.metadata.heroPhotoIndex].link}
        propUrl="/set/{data.params}"
    />

    <SetHeader metadata={data.metadata} />
    <img src={data.metadata.builtImage} alt="{data.metadata.name} Final Build" />
    <Writeup />
    <Dates dates={data.metadata.dates} />

    {#each images as image}
        <figure>
            <img src={image.link} alt={image.altText} />
            <figcaption>{image.altText}</figcaption>
        </figure>
    {/each}
</main>

<style>
    .set-main {
        max-width: min(94%, 1000px);
        margin:0 auto;
        display: flex;
        flex-direction: column;
        align-items: center;
    }
    img {
        max-height: 90vh;
    }
    figure {
        background-color: var(--image-wrap-color);
        margin: 1rem 0;
        border-bottom-left-radius: var(--border-radius);
        border-bottom-right-radius: var(--border-radius);
    }
    figcaption {
        line-height: 2rem;
    }
    @media(prefers-color-scheme: light) {
        figure {
            /* from tinycss's vars */
            background-color: var(--background-body);
        }
        figcaption {
            border-bottom: 1px solid black;
            border-right: 1px solid black;
            border-bottom-right-radius: var(--border-radius);
        }
    }
</style>

// pages/set/[...slug].vue
<script setup lang="ts">
import Dates from '~/components/content/dates.vue';
import setHeader from '~/components/content/set-header.vue';

const { path } = useRoute();
const setData = await queryContent().where({ _path: path }).findOne();
</script>

<template>
  <v-sheet :color="setData.theme1" class="stats">
    <v-card class="blog">
      <setHeader :setData="setData" />
      <v-img :src="setData.builtImage" :alt="`${setData.name} Brickset DB Image`" class="lego-image" />
      <v-divider class="divider"></v-divider>
      <section class="writeup">
        <ContentDoc />
        <Dates :dates="setData.dates" />
      </section>
    </v-card>

    <v-card v-for="photo in setData.photos" class="image-container">
      <v-img :src="photo.link" :alt="photo.altText" class="align-end lego-image">
        <v-card-title class="photo-label" v-text="photo.altText"></v-card-title>
      </v-img>
    </v-card>
  </v-sheet>
</template>

<style scoped>
.stats {
  padding: 2rem;
}

.image-container {
  margin-top: 1rem;
}

@media screen and (max-width: 500px) {
  header {
    margin-bottom: 0.5rem;
  }

  .stats {
    padding: 0;
  }

  .image-container {
    margin-top: 0.5rem;
  }
}

.photo-label {
  white-space: normal;
}

.divider {
  margin: 1rem;
}

a {
  color: white;
  text-decoration-color: white;
}

.writeup {
  display: flex;
  flex-direction: column;
  align-items: center;
}

.lego-image {
  height: auto;
  max-height: 90vh;
}

.blog {
  padding: 1rem;
}
</style>
